/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    ACard: typeof import('ant-design-vue/es')['Card']
    ACascader: typeof import('ant-design-vue/es')['Cascader']
    ACol: typeof import('ant-design-vue/es')['Col']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADivider: typeof import('ant-design-vue/es')['Divider']
    AEmpty: typeof import('ant-design-vue/es')['Empty']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AInput: typeof import('ant-design-vue/es')['Input']
    ALayout: typeof import('ant-design-vue/es')['Layout']
    ALayoutContent: typeof import('ant-design-vue/es')['LayoutContent']
    ALayoutHeader: typeof import('ant-design-vue/es')['LayoutHeader']
    ALayoutSider: typeof import('ant-design-vue/es')['LayoutSider']
    AModal: typeof import('ant-design-vue/es')['Modal']
    ARangePicker: typeof import('ant-design-vue/es')['RangePicker']
    ARow: typeof import('ant-design-vue/es')['Row']
    ArrowDownOutlined: typeof import('@ant-design/icons-vue')['ArrowDownOutlined']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASelectOption: typeof import('ant-design-vue/es')['SelectOption']
    ASpace: typeof import('ant-design-vue/es')['Space']
    AStatistic: typeof import('ant-design-vue/es')['Statistic']
    ASwitch: typeof import('ant-design-vue/es')['Switch']
    ATabPane: typeof import('ant-design-vue/es')['TabPane']
    ATabs: typeof import('ant-design-vue/es')['Tabs']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATypographyLink: typeof import('ant-design-vue/es')['TypographyLink']
    BarChart: typeof import('./../src/components/Charts/Bars/BarChart.vue')['default']
    Bars: typeof import('./../src/components/Charts/Bars/index.vue')['default']
    CenterGrid: typeof import('./../src/designer/CenterGrid/index.vue')['default']
    CloseOutlined: typeof import('@ant-design/icons-vue')['CloseOutlined']
    DeleteOutlined: typeof import('@ant-design/icons-vue')['DeleteOutlined']
    EditOutlined: typeof import('@ant-design/icons-vue')['EditOutlined']
    EyeOutlined: typeof import('@ant-design/icons-vue')['EyeOutlined']
    HeaderBar: typeof import('./../src/designer/HeaderBar/index.vue')['default']
    HelloWorld: typeof import('./../src/components/HelloWorld.vue')['default']
    LeftPanel: typeof import('./../src/designer/LeftPanel/index.vue')['default']
    Lines: typeof import('./../src/components/Charts/Lines/index.vue')['default']
    LinkOutlined: typeof import('@ant-design/icons-vue')['LinkOutlined']
    Pies: typeof import('./../src/components/Charts/Pies/index.vue')['default']
    RadarChartOutlined: typeof import('@ant-design/icons-vue')['RadarChartOutlined']
    RenderCard: typeof import('./../src/designer/CenterGrid/renderCard.vue')['default']
    RenderExtra: typeof import('./../src/designer/CenterGrid/renderExtra.vue')['default']
    RenderGrid: typeof import('./../src/designer/RenderGrid/index.vue')['default']
    RightSetting: typeof import('./../src/designer/RightSetting/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveOutlined: typeof import('@ant-design/icons-vue')['SaveOutlined']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
    SettingTitle: typeof import('./../src/components/SettingTitle/index.vue')['default']
    Statistic: typeof import('./../src/components/Basic/Statistic/index.vue')['default']
    ThunderboltOutlined: typeof import('@ant-design/icons-vue')['ThunderboltOutlined']
  }
}
